# Customized default MunkiReport Dashboard

display_name: Default
hotkey: d

0:
    client: {  }
    messages: {  }
1:
    pending: {  }
    pending_apple: {  }
    pending_munki: {  }
2:
    munki: {  }
    detectx: {  }
    smart_overall_health_test:  {  }
3:
    sip: {  }
    gatekeeper: {  }
    filevault_status: {  }
4:
    warranty: {  }
    new_clients: {  }
    power_battery_condition: {  }
    power_battery_health: {  }
5:
    disk_report: {  }
    uptime: {  }
    firmwarepw: {  }
6:
    network_location: {  }
    munki_versions: {  }
    users_local_admins: {  }
    duplicated_computernames: {  }
    modified_computernames: {  }
    bound_to_ds: {  }
    installed_memory: {  }
7:
    os: {  }
    osbuild:  {  }
8:
    hardware_age: {  }
    memory: {  }
9:
    network_vlan: {  }
